### PR TITLE
added first London restaurant

### PR DESCRIPTION
**Pull request by photoangell**
Added first London, GB restaurant. 
As London is both city and state I didn't create an extra directory, please amend if you feel this is required.

### CODE REVIEW

**Comment by fromzeroedu** [comment]
Looks good, congrats!

**Comment by fromzeroedu** [comment]
Hi!

As promised, since you completed the Git course and project I am offering you a completely free access to my new course, "Professional Backend Web Development with Python Flask".

Just click on the link below to gain access:
 https://www.udemy.com/professional-backend-web-development-with-python-flask/?couponCode=GITCOURSE100

Please do not share this coupon with anyone, as it's only meant for users who completed the Git course and project and there's a limited number of them.

I am looking forward to your feedback and, if you like the course, your review.

Let me know if you have any questions by emailing jorge@fromzero.io

Cheers!

-- Jorge Escobar
@FromZeroEdu

**Comment by photoangell** [comment]
thanks very much.

looks very interesting. I've been thinking about looking at Node.js as a
backend web dev tool - how does it compare to Python?

S

**Comment by fromzeroedu** [comment]
I think Node.js is a really good competitor for backend web application development. 

I think the top reason I'd choose it would be if I wanted to have JavaScript as the primary language end to end (from frontend to backend).

Another good reason could be if the application type is an asynchronous type of application (like a chat room app or a twitter feed). Having said that, Python has Tornado which is a very good async solution.

Having said that, I believe Python is better suited for general Web applications because of it's real Object Oriented design (JavaScript is not Object Oriented), it's age (Python is much more proven in production environments because it's older) and community (it's easier for find Python developers than good JavaScript developers -- jQuery is not JavaScript).

But if you're trying things out, learn both! You'll be a better developer because of it!

**Comment by photoangell** [comment]
Thanks for the reply.

I am primarily a backend web developer, though in Classic ASP, so I really
need to update my skills. Dont want to go down the .net route, so am
looking to switch over to the open source world.

I've a lot of experience with Javascript (in the front end) - so it kind of
makes sense to look at it at the backend as I change my skills.
But I've had a play around with some basic python and quite like it so far.
It's really clicking with me.

Where do you think the really interesting work is going to be in the web
dev world in the future?

S

**Comment by fromzeroedu** [comment]
It depends on what you define as "future". Is it 1 year from now or 10 years?

I can tell you in the next 2 - 3 years we're going to see a major revolution on the Javascript side, mainly thanks to ECMAScript6 (the next version of JS) which will allow the development of more complex frontend and backend applications written in pure JS. I'm really excited about this!

Having said that, I see Python continue its adoption of a lot of high profile projects and the job market for it (at least here in the U.S. is exploding). I think in 2 years Python 3 should be the standard.

The other major shift I see is the explosion of mobile and its continued market share versus desktop applications, so I would highly recommend to either learn Swift or the Java SDK for Android, or, if you want to keep on the Javascript/HTML side, Cordova or Phonegap.

That's what I have for the moment!

-- Jorge

**Comment by photoangell** [comment]
Thanks Jorge,

That's really useful info. I was thinking long term. I'm 44 now, but
there's still plenty of coding years left in me :-)

S

**Pull request merged**
