### PR TITLE
Added New_Jersey/Edison

### PR DESCRIPTION
**Pull request by geekdad**

### CODE REVIEW

**Comment by fromzeroedu** [comment]
Looks great, congratulations!

**Comment by fromzeroedu** [comment]
Hi!

As promised, since you completed the Git course and project I am offering you a completely free access to my new course, "Professional Backend Web Development with Python Flask".

Just click on the link below to gain access:
https://www.udemy.com/professional-backend-web-development-with-python-flask/?couponCode=GITCOURSE100

Please do not share this coupon with anyone, as it's only meant for users who completed the Git course and project and there's a limited number of them.

I am looking forward to your feedback and, if you like the course, your review.

Let me know if you have any questions by emailing jorge@fromzero.io

Cheers!

-- Jorge Escobar
@FromZeroEdu

**Comment by geekdad** [comment]
Hey Jorge,

I already signed up for your Flask course the other day with the $5 coupon.
:)

Hock

**Comment by fromzeroedu** [comment]
Got it. Well, you can use that coupon and gift it to someone you know could use it.

Hope you're enjoying the Python course and let me know if you have any questions.

Cheers!

-- Jorge

**Pull request merged**
