### PR TITLE
Added Portland, OR

### PR DESCRIPTION
**Pull request by richie2000**
My fav restaurant

### CODE REVIEW

**Comment by richie2000** [comment]
Thanks. 
Great course.

**Comment by fromzeroedu** [comment]
Thanks Richie. I appreciate it if you can add a review if you liked it and what you liked/didn't like it. Of course, when you have time. :smile:

**Comment by fromzeroedu** [comment]
Hi!

As promised, since you completed the Git course and project I am offering you a completely free access to my new course, "Professional Backend Web Development with Python Flask".

Just click on the link below to gain access:
 https://www.udemy.com/professional-backend-web-development-with-python-flask/?couponCode=GITCOURSE100

Please do not share this coupon with anyone, as it's only meant for users who completed the Git course and project and there's a limited number of them.

I am looking forward to your feedback and, if you like the course, your review.

Let me know if you have any questions by emailing jorge@fromzero.io

Cheers!

-- Jorge Escobar
@FromZeroEdu

**Comment by richie2000** [comment]
Hi Jorge,

You said that the Python-Flask course would be for free, but Udemy charged
me $5.

- Richie

**Comment by fromzeroedu** [comment]
Hi Richie,

Didn't you click the link on the post above? That's a free coupon.

How did you sign up then?

-- Jorge

**Comment by richie2000** [comment]
Fail.. I used the wrong URL.
https://www.udemy.com/professional-backend-web-development-with-python-flask/?couponCode=GITCOURSE5PROMOMARCH2015&utm_campaign=email&utm_source=sendgrid.com&utm_medium=email#/

There were a few promo emails and I just clicked through on the wrong one.
No big deal.. it's only $5.
Think of it as a tip for the great Git course.
(Hope Flask is just as good)

I'm new to web dev, so I was originally thinking about using Django because
it's the most popular.
But it seems overkill for my Raspberry Pi project and Flask is a better and
simpler fit.

Thanks
- Richie

**Pull request merged**
