### PR TITLE
add tel aviv restraunt

### PR DESCRIPTION
**Pull request by yanivdror**
hi
i enjoyed your git course and im adding israel tel aviv restraunt

### CODE REVIEW

**Comment by fromzeroedu** [comment]
Oh, that's very interesting. Okay, so then you just need to correct the file name for "restaurants.md". No need to put any province.

Thanks!

**Comment by yanivdror** [comment]
added second commit with fixed restaurants.md name

**Comment by fromzeroedu** [comment]
Almost there! Please git rm (delete) the first file (restraunts.md), and commit and push, as I think I'd be adding both files.

**Comment by yanivdror** [comment]
hope it finaly fine 
???

**Comment by fromzeroedu** [comment]
You did it! Awesome job! Merging now...

**Pull request merged**
